#pragma config(Sensor, dgtl1,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  driveEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, outerLiftEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           leftLiftMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           outerLiftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           clawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftCarrierMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCarrierMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightLiftMotor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Constants 2017.c"
#include "Functions 2017.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	runClaw(halfPower);
	while(liftSensor ISUNDER zone1 OR driveSensor ISUNDER carrierDistance)
	{
		if(liftSensor ISUNDER zone1)
		{
			runInnerLift(maxPower);
			runOuterLift(reverseThreeQuarterPower);
		}
		else
		{
			runInnerLift(liftStopPower);
			runOuterLift(threeQuarterPower);
			runCarrier(reverseMaxPower);
		}
		if(driveSensor ISUNDER carrierDistance)
		{
			runDrive(maxPower);
		}
		else
		{
			runDrive(stopPower);
		}
	}
	runOuterLift(stopPower);
	holdUp(carrierWaitTime);
	resetSensor(driveEncoder);
	runForward(carrierPickUpDistance, maxPower);
	wait();
	resetSensor(driveEncoder);
	runCarrier(maxPower);
	holdUp(carrierLightTime);
	runCarrier(stopPower);
	while(driveSensor ISOVER straightBack OR liftSensor ISOVER startLocation)
	{
		if(liftSensor ISOVER startLocation)
		{
			runInnerLift(reverseMaxPower);
		}
		else
		{
			runClaw(reverseMaxPower);
		}
		if(driveSensor ISOVER straightBack)
		{
			runBackward(straightBack, reverseMaxPower);
		}
		else
		{
			runDrive(stopPower);
		}
	}
	runClaw(halfPower);
	wait();
	resetSensor(driveEncoder);
	while(driveSensor ISUNDER turnRight135Distance OR liftSensor ISUNDER zone1)
	{
		if(driveSensor ISUNDER turnRight135Distance)
		{
			turnRight(maxPower);
		}
		else
		{
			runDrive(stopPower);
		}
		if(liftSensor ISUNDER zone1)
		{
			runInnerLift(maxPower);
		}
		else
		{
			runInnerLift(liftStopPower);
		}
	}
	runForward(toMiddle, maxPower);
	turnOnlyRight(turnRight90Distance, maxPower);
	runForward(farZoneDistance, maxPower);
	runCarrier(reverseMaxPower);
	holdUp(carrierLightTime);
	runCarrier(stopPower);
	runBackward(reverseFarZoneDistance, reverseHalfPower);
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	bool autoClose = false;
	bool autoOpen = false;
	while(true)
	{
		rightDrive = rightJoystick;
		leftDrive = leftJoystick;
		if(joint1Button IS PRESSED)
		{
			if(liftSensor ISUNDER zone2)
			{
				runInnerLift(maxPower);
				runOuterLift(reverseMaxPower);
			}
			else
			{
				runInnerLift(halfPower);
				runOuterLift(reverseMaxPower);
			}
		}
		else if(joint2Button IS PRESSED)
		{
			runInnerLift(reverseMaxPower);
			runOuterLift(maxPower);
		}
		else if(axisUpButton IS PRESSED)
		{
			runInnerLift(threeQuarterPower);
			runOuterLift(reverseQuarterPower);
		}
		else if(axisDownButton IS PRESSED)
		{
			runInnerLift(reverseThreeQuarterPower);
			runOuterLift(quarterPower);
		}
		else
		{
			if(innerLiftUpButton IS PRESSED)
			{
				if(liftSensor ISUNDER zone2)
				{
					innerLiftUp();
				}
				else
				{
					innerLiftSlowUp();
				}
			}
			else if(innerLiftDownButton IS PRESSED)
			{
				if(liftSensor ISUNDER zone1)
				{
					innerLiftSlowDown();
				}
				else
				{
					innerLiftDown();
				}
			}
			else
			{
				if(liftSensor ISUNDER zone1)
				{
					zone1InnerLiftStop();
				}
				else if(liftSensor ISOVER zone2)
				{
					zone2InnerLiftStop();
				}
				else
				{
					innerLiftStop();
				}
			}
			if(outerLiftUpButton IS PRESSED)
			{
				if(liftSensor ISUNDER zone1)
				{
					outerLiftUp();
				}
				else if(liftSensor ISOVER zone2)
				{
					if(outerLiftSensor ISUNDER zone32)
					{
						outerLiftUp();
					}
					else
					{
						outerLiftSlowUp();
					}
				}
				else
				{
					if(outerLiftSensor ISUNDER zone22)
					{
						outerLiftUp();
					}
					else
					{
						outerLiftSlowUp();
					}
				}
			}
			else if(outerLiftDownButton IS PRESSED)
			{
				if(liftSensor ISUNDER zone1)
				{
					if(outerLiftSensor ISUNDER zone11)
					{
						outerLiftSlowDown();
					}
					else
					{
						outerLiftDown();
					}
				}
				else if(liftSensor ISOVER zone2)
				{
					if(outerLiftSensor ISUNDER zone31)
					{
						outerLiftSlowDown();
					}
					else
					{
						outerLiftDown();
					}
				}
				else
				{
					outerLiftDown();
				}
			}
			else
			{
				if(liftSensor ISUNDER zone1)
				{
					if(outerLiftSensor ISUNDER zone11)
					{
						zone1OuterLiftStop();
					}
					else if(outerLiftSensor ISOVER zone12)
					{
						zone2OuterLiftStop();
					}
					else
					{
						zone2OuterLiftStop();
					}
				}
				else if(liftSensor ISOVER zone2)
				{
					if(outerLiftSensor ISUNDER zone31)
					{
						zone1OuterLiftStop();
					}
					else if(outerLiftSensor ISOVER zone32)
					{
						zone2OuterLiftStop();
					}
					else
					{
						outerLiftStop();
					}
				}
				else
				{
					if(outerLiftSensor ISUNDER zone21)
					{
						zone1OuterLiftStop();
					}
					else if(outerLiftSensor ISOVER zone22)
					{
						zone2OuterLiftStop();
					}
					else
					{
						outerLiftStop();
					}
				}
			}
		}
		if(carrierUpButton IS PRESSED)
		{
			carrierUp();
		}
		else if(carrierDownButton IS PRESSED)
		{
			carrierDown();
		}
		else
		{
			carrierStop();
		}
		if(clawOpenButton IS PRESSED OR autoOpen)
		{
			if(clawCloseButton IS PRESSED)
			{
				autoOpen = false;
				autoClose = true;
			}
			else if(clawOpenButton ISNOT PRESSED)
			{
				clawSlowOpen();
			}
			else
			{
				clawOpen();
				autoClose = false;
				autoOpen = true;
			}
		}
		else if(clawCloseButton IS PRESSED OR autoClose)
		{
			autoClose = true;
			autoOpen = false;
			clawClose();
		}
		else
		{
			clawStop();
		}
		if(batteryLevel ISOVER batteryHigh)
		{
			switchLED(greenLED, ON);
			switchLED(yellowLED, OFF);
			switchLED(redLED, OFF);
		}
		else if(batteryLevel ISOVER batteryLow AND batteryLevel ISUNDER batteryHigh)
		{
			switchLED(greenLED, OFF);
			switchLED(yellowLED, ON);
			switchLED(redLED, OFF);
		}
		else
		{
			switchLED(greenLED, OFF);
			switchLED(yellowLED, OFF);
			switchLED(redLED, ON);
		}
	}
}
