#define rightJoystick vexRT(Ch2)
#define leftJoystick vexRT(Ch3)
#define rightDrive motor[rightMotor]
#define leftDrive motor[leftMotor]
#define IS ==
#define ISUNDER <=
#define ISOVER >=
#define ISNOT !=
#define PRESSED 1
#define ON 1
#define OFF 0
#define innerLiftUpButton vexRT(Btn5U)
#define innerLiftDownButton vexRT(Btn5D)
#define outerLiftUpButton vexRT(Btn6U)
#define outerLiftDownButton vexRT(Btn6D)
#define carrierUpButton vexRT(Btn8L)
#define carrierDownButton vexRT(Btn8R)
#define clawOpenButton vexRT(Btn8D)
#define clawCloseButton vexRT(Btn8U)
#define joint1Button vexRT(Btn7L)
#define joint2Button vexRT(Btn7R)
#define axisDownButton vexRT(Btn7D)
#define axisUpButton vexRT(Btn7U)
#define liftSensor SensorValue(liftEncoder)
#define outerLiftSensor SensorValue(outerLiftEncoder)
#define driveSensor SensorValue(driveEncoder)
#define AND &&
#define OR ||
#define maxPower 127
#define reverseMaxPower -127
#define outerLiftPower 95
#define reverseOuterLiftPower -95
#define halfPower 63
#define reverseHalfPower -63
#define outerMatchPower 108
#define reverseOuterMatchPower -108
#define slowPower 10
#define reverseSlowPower -10
#define liftStopPower 15
#define reverseLiftStopPower -15
#define stopPower 0
#define quarterPower 32
#define reverseQuarterPower -32
#define threeQuarterPower 95
#define reverseThreeQuarterPower -95
#define zone1 95
#define zone2 140
#define highLiftZone 105
#define lowLiftZone 70
#define zone11 1132
#define zone12 1339
#define zone21 615
#define zone22 771
#define zone31 166
#define zone32 281
#define innerLiftLowLocation1 129
#define innerLiftLowLocation2 149
#define innerLiftHighLocation1 105
#define innerLiftHighLocation2 125
#define outerLiftLowLocation1 -335
#define outerLiftLowLocation2 -315
#define outerLiftHighLocation1 0
#define outerLiftHighLocation2 0
#define batteryLevel nAvgBatteryLevel
#define batteryHigh 7500
#define batteryLow 7000
#define carrierDistance 500
#define carrierPickUpDistance 500
#define carrierWaitTime 500
#define carrierLightTime 500
#define carrierHeavyTime 500
#define startLocation 0
#define turnLeft180Distance -500
#define turnRight180Distance 500
#define straightBack -500
#define turnRight135Distance 500
#define turnLeft135Distance -500
#define toMiddle 500
#define turnRight90Distance 500
#define turnLeft90Distance -500
#define farZoneDistance 500
#define nearZoneDistance 500
#define reverseFarZoneDistance -500
#define reverseNearZoneDistance -500
