#pragma config(Sensor, dgtl1,  liftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  outerLiftEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  driveEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           rightLiftMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           outerLiftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftCarrierMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightCarrierMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftLiftMotor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Isabelle_Constants.c"
#include "Isabelle_Functions.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}


task autonomous()
{
	runClaw(halfPower);
	while(liftSensor ISUNDER zone1 OR driveSensor ISUNDER carrierDistance)
	{
		if(liftSensor ISUNDER zone1)
		{
			runInnerLift(fullPower);
			runOuterLift(reverseThreeQuarterPower);
		}
		else
		{
			runInnerLift(stayPower);
			runOuterLift(threeQuarterPower);
			runCarrier(reverseFullPower);
		}
		if(driveSensor ISUNDER carrierDistance)
		{
			runDrive(fullPower);
		}
		else
		{
			runDrive(reverseStayPower);
			runOuterLift(threeQuarterPower);
			runCarrier(reverseFullPower);
		}
		if(driveSensor ISUNDER carrierDistance)
		{
			runDrive(fullPower);
		}
		else
		{
			runDrive(stopPower);
		}
	}
	runOuterLift(stopPower);
	holdUp(carrierWaitTime);
	resetSensor(driveEncoder);
	runForward(carrierPickUpDistance, fullPower);
	wait();
	resetSensor(driveEncoder);
	runCarrier(fullPower);

	while(driveSensor ISOVER straightBack OR liftSensor ISOVER startLocation)
	{
		if(liftSensor ISOVER startLocation)
		{
			runInnerLift(reverseFullPower);
		}
		else
		{
			runClaw(reverseFullPower);
		}

		if(driveSensor ISOVER straightBack)
		{
			runBackward(straightBack, fullPower);
		}
		else
		{
			runDrive(stopPower);
		}
	}
	runClaw(halfPower);
	wait();
	resetSensor(driveEncoder);
	while(driveSensor ISOVER straightBack OR liftSensor ISOVER startLocation)
	{
		if(liftSensor ISOVER startLocation)
		{
			runInnerLift(reverseFullPower);
		}
		else
		{
			runClaw(reverseFullPower);
		}
		if(driveSensor ISOVER straightBack)
		{
			runBackward(straightBack, reverseFullPower);
		}
		else
		{
			runDrive(stopPower);
		}
	}
	runClaw(halfPower);
	wait();
	resetSensor(driveEncoder);
	while(driveSensor ISUNDER turnRight135Distance OR liftSensor ISUNDER zone1)
	{
		if(driveSensor ISUNDER turnRight135Distance)
		{
			turnRight(fullPower);
		}
		else
		{
			runDrive(stopPower);
		}
		if(liftSensor ISUNDER zone1)
		{
			runInnerLift(fullPower);
		}
		else
		{
			runInnerLift(stayPower);
		}
	}
	runForward(toMiddle, fullPower);
	turnOnlyRight(turnRight90Distance, fullPower);
	runForward(farZoneDistance, fullPower);
	runCarrier(reverseFullPower);
	holdUp(carrierLightTime);
	runCarrier(stopPower);
	runBackward(reverseFarZoneDistance, reverseHalfPower);
}

task usercontrol()
{
	bool autoOpen = false;
	bool autoClose = false;
	resetSensor(liftEncoder);
	resetSensor(outerLiftEncoder);

	while(true)
	{
		rightDrive = rightJoystick;
		leftDrive = leftJoystick;

		if(carrierUpBtn IS PRESSED)
		{
			carrierUp();
		}
		else if(carrierDownBtn IS PRESSED)
		{
			carrierDown();
		}
		else
		{
			carrierStop();
		}

		if(clawOpenBtn IS PRESSED OR autoOpen)
		{
			if(clawCloseBtn IS PRESSED)
			{
				autoOpen = false;
				autoClose = true;
			}
			else if(clawOpenBtn ISNOT PRESSED)
			{
				clawSlowOpen();
			}
			else
			{
				autoClose = false;
				autoOpen = true;
				clawOpen();
			}
		}
		else if(clawCloseBtn IS PRESSED OR autoClose)
		{
			autoClose = true;
			autoOpen = false;
			clawClose();
		}
		else
		{
			clawStop();
		}


		if(joint1Btn IS PRESSED )
		{
			if(liftSensor ISUNDER zone2)
			{
				runInnerLift(fullPower);
				runOuterLift(reverseFullPower);
			}
			else
			{
				runInnerLift(halfPower);
				runOuterLift(reverseFullPower);
			}
		}
		else if(joint2Btn IS PRESSED)
		{
			runInnerLift(reverseFullPower);
			runOuterLift(fullPower);
		}

		else if(axisUpBtn IS PRESSED)
		{
			runInnerLift(threeQuarterPower);
			runOuterLift(reverseQuarterPower);
		}
		else if(axisDownBtn IS PRESSED)
		{
			runInnerLift(reverseThreeQuarterPower);
			runOuterLift(quarterPower);
		}


		else
		{
			if(innerLiftUpBtn IS PRESSED)
			{
				if(liftSensor ISUNDER zone2)
				{
					innerLiftUp();
				}
				else
				{
					innerLiftSlowUp();
				}
			}
			else if(innerLiftDownBtn IS PRESSED)
			{
				if(liftSensor ISUNDER zone1)
				{
					innerLiftSlowDown();
				}
				else
				{
					innerLiftDown();
				}
			}
			else
			{
				if(liftSensor ISUNDER zone1)
				{
					zone1InnerLiftStay();
				}
				else if(liftSensor ISOVER zone2)
				{
					zone2InnerLiftStay();
				}
				else
				{
					innerLiftStop();
				}
			}

			if(outerLiftUpBtn IS PRESSED)
			{
				if(liftSensor ISUNDER zone1)
				{
					outerLiftUp();
				}
				else if(liftSensor ISOVER zone2)
				{
					if(outerLiftSensor ISUNDER zone32)
					{
						outerLiftUp();
					}
					else
					{
						outerLiftSlowUp();
					}
				}
				else
				{
					if(outerLiftSensor ISUNDER zone22)
					{
						outerLiftUp();
					}
					else
					{
						outerLiftSlowUp();
					}
				}
			}
			else if(outerLiftDownBtn IS PRESSED)
			{
				if(liftSensor ISUNDER zone1)
				{
					if(outerLiftSensor ISUNDER zone11)
					{
						outerLiftSlowDown();
					}
					else
					{
						outerLiftDown();
					}
				}
				else if(liftSensor ISOVER zone2)
				{
					if(outerLiftSensor ISUNDER zone31)
					{
						outerLiftSlowDown();
					}
					else
					{
						outerLiftDown();
					}
				}
				else
				{
					outerLiftDown();
				}
			}
			else
			{
				if(liftSensor ISUNDER zone1)
				{
					if(outerLiftSensor ISUNDER zone11)
					{
						zone1OuterLiftStay();
					}
					else if(outerLiftSensor ISOVER zone12)
					{
						zone2OuterLiftStay();
					}
					else
					{
						outerLiftStop();
					}
				}
				else
				{
					if(outerLiftSensor ISUNDER zone21)
					{
						zone1OuterLiftStay();
					}
					else if(outerLiftSensor ISOVER zone22)
					{
						zone2OuterLiftStay();
					}
					else
					{
						outerLiftStop();
					}
				}
			}
		}
	}
}
