#define rightDrive motor(rightMotor)
#define leftDrive motor(leftMotor)
#define rightJoystick vexRT(Ch2)
#define leftJoystick vexRT(Ch3)
#define innerLiftUpBtn vexRT(Btn5U)
#define innerLiftDownBtn vexRT(Btn5D)
#define outerLiftUpBtn vexRT(Btn6U)
#define outerLiftDownBtn vexRT(Btn6D)
#define axisUpBtn vexRT(Btn7U)
#define axisDownBtn vexRT(Btn7D)
#define joint1Btn vexRT(Btn7L)
#define joint2Btn vexRT(Btn7R)
#define clawOpenBtn vexRT(Btn8D)
#define clawCloseBtn vexRT(Btn8U)
#define carrierUpBtn vexRT(Btn8L)
#define carrierDownBtn vexRT(Btn8R)
#define PRESSED 1
#define IS ==
#define ISUNDER <=
#define ISOVER >=
#define ISNOT !=
#define AND &&
#define OR ||
#define fullPower 127
#define reverseFullPower -127
#define halfPower 64
#define reverseHalfPower -64
#define quarterPower 32
#define reverseQuarterPower -32
#define threeQuarterPower 95
#define reverseThreeQuarterPower - 95
#define slowPower 10
#define reverseSlowPower -10
#define stayPower 15
#define reverseStayPower -15
#define stopPower 0
#define outerLiftPower 95
#define reverseOuterLiftPower -95
#define outerMatchPower 108
#define reverseOuterMatchPower -108
#define zone1 95
#define zone2 140
#define zone11 1132
#define zone12 1339
#define zone21 615
#define zone22 771
#define zone31 166
#define zone32 281
#define liftSensor SensorValue(liftEncoder)
#define outerLiftSensor SensorValue(outerLiftEncoder)
#define driveSensor SensorValue(driveEncoder)
#define batteryLevel nAvgBatteryLevel
#define batteryHigh 7500
#define batteryLow 7000
#define carrierDistance 500
#define carrierPickUpDistance 500
#define carrierWaitTime 500
#define straightBack 500
#define startLocation 0
#define carrierLightTime 500
#define carrierHeavyTime 500
#define turnLeft180Distance -500
#define turnRight180Distance 500
#define turnRight135Distance 500
#define turnLeft135Distance -500
#define toMiddle 500
#define turnRight90Distance 500
#define turnLeft90Distance -500
#define farZoneDistance 500
#define nearZoneDistance 500
#define reverseFarZoneDistance -500
#define reverseNearZoneDistance -500
